In [1]:
## Questions:

## 1. Create a ndarray of first five multiples of 6.
## 2. Convert the 1D array created in Q1 to 3D, and display the number of dimensions of the latter.
## 3. Create a 2D array where first 5 prime numbers occupy the 1st dimension & the first 5 composite numbers in the 2nd 
##    dimension.
## 4. From the array created in Q3, retrieve the last element from 2nd dimension.
## 5. Retrieve the 2nd, 3rd and 4th elements from both dimensions of the 2D array created in Q3.
## 6. Display the data type of the array created in Q1, and change it to float.
## 7. Create a 1D array of twelve zeros and reshape it to a 2D array of shape (3,4).
## 8. Flatten the 2D array that you created in the previous question back to 1D.
## 9. Consider an array [24,45,67,90,123,367]. Find the indexes where the values are even.
## 10. Create two arrays, one with first 5 odd numbers and the other with first 5 even numbers. 
##     Then concatenate both the arrays along columns.
## 11. Subtract the even number array from the odd number array created in Q10.
## 12. Create two matrices of the squares and cubes of first 4 natural numbers, and perform matrix multiplication. 
##     Also, obtain the transpose of the matrix resulting from the multiplication.

In [ ]:
# Part 2 Questions:

# 1.  Write a NumPy program to create a null vector of size 10 and update sixth value to 11.
# [ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
# Update sixth value to 11
# [ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

# 2.  Write a NumPy program to convert a list and tuple into arrays. 
# List to array:
# [1 2 3 4 5 6 7 8]
# Tuple to array:
# [[8 4 6]
# [1 2 3]]

# 3. Write a NumPy program to find the real and imaginary parts of an array of complex numbers. 
# Expected Output:
# Original array [ 1.00000000+0.j 0.70710678+0.70710678j]
# Real part of the array:
# [ 1. 0.70710678]
# Imaginary part of the array:
# [ 0. 0.70710678]

# 4. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2. 
# Expected Output:
# Array1: [ 0 10 20 40 60 80]
# Array2: [10, 30, 40, 50, 70, 90]
# Set difference between two arrays:
# [ 0 20 60 80]

# 5. a = np.array([x for x in range(27)]) - convert this 1-D to a 3-D array

# 6. Convert the following array into a boolean and display the ouput
#    a = np.array([[1, 0, 0],
#               [1, 1, 1],
#               [0, 0, 0]])

# 7. Generate a sequence of numbers in the form of a numpy array from 0 to 100 with gaps of 2 numbers, for example: 0, 2, 4 ....

# 8. From 2 numpy arrays, extract the indexes in which the elements in the 2 arrays match:
#    a = np.array([1,2,3,4,5])
#    b = np.array([1,3,2,4,5]) 
    
# 9. Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10

# 10. Following is the provided numPy array. Return array of items by taking the third column from all rows:
#     sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
    
# 11.  Return array of odd rows and even columns from below numpy array
# sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
# [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

# 12. Split the array into four equal-sized sub-arrays:
# a = [[10 11 12]
#  [13 14 15]
#  [16 17 18]
#  [19 20 21]
#  [22 23 24]
#  [25 26 27]
#  [28 29 30]
#  [31 32 33]]

# 13. Replace all odd numbers in the given array with -1:
#     arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 14. Find the positions of:
#     elements in x where its value is more than its corresponding element in y, and
#     elements in x where its value is equals to its corresponding element in y.
#     x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
#     y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

# 15. Convert a 1-D array into a 2-D array with 3 rows
#     arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
    
# 16. Extract the first four columns of this 2-D array
#     arr = np.arange(100).reshape(5,-1)
